### PR TITLE
Update from ActiveRecord 6 to ActiveRecord 7

### PR DESCRIPTION
**Pull request by KludgeKML**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

(This PR follows the Rails 7 update method, but abridged because we don't actually have rails in this app, just active_record)

https://trello.com/c/cOkOCfta/534-upgrade-transition-from-rails-61x-to-70x
https://trello.com/c/oBxeOF70/1148-rails-7-update-bouncer

Do not merge until a matching Transition PR is ready. (NOTE: This is now with Publishing so they can merge when their Transition update is done).

### CODE REVIEW

**Review by edwardkerry — COMMENTED** [review]
this looks fine but if we have no deprecations could/should we lose the empty commit and just note this on the trello card/PR message?

**Comment by KludgeKML** [comment]
> this looks fine but if we have no deprecations could/should we lose the empty commit and just note this on the trello card/PR message?

Good question! I kept it in because I thought it might be a useful signal if all the similar PRs were the same. But I'm not so certain of that that I'd die on that hill. I think if your instinct is not to have it, I'll remove it.

**Review by edwardkerry — APPROVED** [review]
This looks good to me but I've spotted a comment in the Gemfile that this should "ideally" be done in tandem with Transition - is it worth holding off on this until Transition also bumps Rails/ActiveRecord?

**Comment by KludgeKML** [comment]
Note - blocked until the Transition PR is ready.

**Comment by brucebolt** [comment]
We have a PR for transition: https://github.com/alphagov/transition/pull/1166.

Hopefully this can be merged soon.

**Comment by brucebolt** [comment]
@KludgeKML We're ready to merge the transition PR.  Looks like this will now need rebasing before we can merge this in at the same time.

**Pull request merged**
